name = "it-era-admin-panel"
compatibility_date = "2024-08-25"

[[pages_build_output_dir = "dist"]]

[env.production]
name = "it-era-admin-panel-production"

[env.staging]
name = "it-era-admin-panel-staging"

# Custom domain configuration
[[pages_custom_domains]]
domain = "admin.it-era.it"

# Environment variables for different environments
[env.production.vars]
API_BASE_URL = "https://it-era-admin-auth-production.bulltech.workers.dev"
ENVIRONMENT = "production"

[env.staging.vars]
API_BASE_URL = "https://it-era-admin-auth-staging.bulltech.workers.dev"
ENVIRONMENT = "staging"

# Build configuration
[build]
command = "npm run build"
cwd = ""
watch_dir = "admin"

# Headers configuration
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "public, max-age=300"

# Redirects
[[redirects]]
from = "/admin"
to = "/index.html"
status = 200

[[redirects]]
from = "/admin/*"
to = "/index.html"
status = 200