version: '3.8'

services:
  seo-tools:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-era-seo-tools
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - SITE_URL=https://it-era.pages.dev
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-it-era-seo-secret-2024}
    volumes:
      # Mount logs and reports for persistence
      - seo-logs:/opt/seo-tools/logs
      - seo-reports:/opt/seo-tools/reports
      - seo-data:/opt/seo-tools/data
      # Mount configuration from host if needed
      - ./config:/opt/seo-tools/config:ro
      # Mount scripts from host for development (optional)
      # - ./scripts:/opt/seo-tools/scripts:ro
    ports:
      - "9001:9001"  # Supervisor web interface
    networks:
      - seo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Web dashboard for SEO reports
  seo-dashboard:
    image: nginx:alpine
    container_name: it-era-seo-dashboard
    restart: unless-stopped
    volumes:
      - seo-reports:/usr/share/nginx/html/reports:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - seo-network
    depends_on:
      - seo-tools

  # Optional: Log aggregation with ELK stack (lightweight version)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: it-era-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - seo-network
    profiles:
      - monitoring

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: it-era-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - seo-network
    depends_on:
      - elasticsearch
    profiles:
      - monitoring

volumes:
  seo-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/logs
  
  seo-reports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/reports
      
  seo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/data

  elasticsearch-data:
    driver: local

networks:
  seo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16