#!/bin/bash

# Repository Cleanup Script - IT-ERA Project
# Generated by HIVE 3 - Repository Cleanup System
# Date: $(date)

set -e

echo "🧹 REPOSITORY CLEANUP - IT-ERA PROJECT"
echo "======================================"

# Function to display section headers
section_header() {
    echo ""
    echo "📂 $1"
    echo "----------------------------------------"
}

# Check if cleanup directory exists
if [ ! -d "da_cancellare" ]; then
    echo "❌ Error: da_cancellare directory not found!"
    echo "   Run this script from the project root directory."
    exit 1
fi

section_header "CLEANUP SUMMARY"

# Count files in each category
agent_scripts=$(find da_cancellare/agent_scripts -name "*.js" 2>/dev/null | wc -l || echo "0")
reports=$(find da_cancellare/temporary_reports -name "*report*" 2>/dev/null | wc -l || echo "0")
test_files=$(find da_cancellare/test_files -name "*.js" 2>/dev/null | wc -l || echo "0")
validation_batches=$(find da_cancellare/validation_batches -type f 2>/dev/null | wc -l || echo "0")
utility_scripts=$(find da_cancellare/utility_scripts -name "*.js" 2>/dev/null | wc -l || echo "0")

echo "Agent Scripts:     $agent_scripts files"
echo "Reports:          $reports files"
echo "Test Files:       $test_files files"
echo "Validation Files: $validation_batches files"
echo "Utility Scripts:  $utility_scripts files"

section_header "ORGANIZED FILES"

# List agent scripts
if [ -d "da_cancellare/agent_scripts" ] && [ "$(ls -A da_cancellare/agent_scripts)" ]; then
    echo "🤖 Agent Scripts:"
    ls -la da_cancellare/agent_scripts/
fi

# List reports
if [ -d "da_cancellare/temporary_reports" ] && [ "$(ls -A da_cancellare/temporary_reports)" ]; then
    echo ""
    echo "📊 Reports:"
    ls -la da_cancellare/temporary_reports/
fi

section_header "SYSTEM STATUS"

# Check git status
echo "📝 Git Status:"
git status --porcelain | grep -v "da_cancellare/" || echo "   Repository is clean (ignoring da_cancellare/)"

section_header "CLEANUP OPTIONS"

echo "Choose an action:"
echo "1) Keep files organized in da_cancellare/ (recommended)"
echo "2) Permanently delete all files in da_cancellare/"
echo "3) Archive files to cleanup-backup-$(date +%Y%m%d).tar.gz"
echo "4) Exit without changes"

read -p "Enter your choice (1-4): " choice

case $choice in
    1)
        echo "✅ Files remain organized in da_cancellare/ directory"
        echo "   You can review and manually delete when ready."
        ;;
    2)
        read -p "⚠️  Are you sure you want to PERMANENTLY DELETE all files? (yes/no): " confirm
        if [ "$confirm" = "yes" ]; then
            rm -rf da_cancellare/
            echo "🗑️  All cleanup files permanently deleted!"
            git add .
            echo "   Changes staged for commit."
        else
            echo "❌ Deletion cancelled."
        fi
        ;;
    3)
        tar -czf "cleanup-backup-$(date +%Y%m%d).tar.gz" da_cancellare/
        echo "📦 Files archived to cleanup-backup-$(date +%Y%m%d).tar.gz"
        echo "   You can now safely delete da_cancellare/ if desired."
        ;;
    4)
        echo "🚪 Exiting without changes."
        ;;
    *)
        echo "❌ Invalid choice. Exiting."
        exit 1
        ;;
esac

echo ""
echo "🎉 Cleanup script completed!"
echo "======================================="