# IT-ERA Cloudflare Pages Configuration
name = "it-era-website"
compatibility_date = "2024-09-07"
pages_build_output_dir = "web"

# Environment Variables
[vars]
ENVIRONMENT = "production"
SITE_NAME = "IT-ERA"
EMERGENCY_PHONE = "039 888 2041"
COMPANY_EMAIL = "info@it-era.it"
SERVICE_AREA = "Lombardia"
RESPONSE_TIME = "15 minuti"
