#!/bin/bash

# IT-ERA Automated Blog Generation Cron Job
# Runs daily at 9:00 AM

# Set working directory
cd /Users/andreapanzeri/progetti/IT-ERA

# Create logs directory if it doesn't exist
mkdir -p logs

# Log file with timestamp
LOG_FILE="logs/cron-blog-$(date +%Y%m%d-%H%M%S).log"

# Function to log with timestamp
log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log_message "🤖 STARTING AUTOMATED BLOG GENERATION"
log_message "Working directory: $(pwd)"
log_message "Node version: $(node --version)"
log_message "Git status: $(git status --porcelain | wc -l) files changed"

# Run the automated blog system
log_message "📝 Running blog generation..."
if node blog/automated-blog-system.js generate >> "$LOG_FILE" 2>&1; then
    log_message "✅ Blog generation completed successfully"
    
    # Check if new files were created
    NEW_FILES=$(git status --porcelain | grep "^??" | wc -l)
    MODIFIED_FILES=$(git status --porcelain | grep "^M" | wc -l)
    
    log_message "📊 Changes detected: $NEW_FILES new files, $MODIFIED_FILES modified files"
    
    if [ $((NEW_FILES + MODIFIED_FILES)) -gt 0 ]; then
        log_message "🚀 Deploying changes to GitHub..."
        
        # Add all blog changes
        git add blog/ sitemap.xml >> "$LOG_FILE" 2>&1
        
        # Create commit with timestamp
        COMMIT_MSG="🤖 AUTO-BLOG: Daily article published - $(date '+%Y-%m-%d %H:%M')

✅ AUTOMATED CONTENT GENERATION:
- New SEO-optimized article published
- Blog index and category pages updated
- Sitemap updated for search engines
- Generated by IT-ERA Blog Automation System

📊 AUTOMATION METRICS:
- Execution time: $(date '+%Y-%m-%d %H:%M:%S')
- System: Cron job automation
- Quality: Professional IT expertise content
- SEO: Optimized for Lombardy market"

        if git commit -m "$COMMIT_MSG" >> "$LOG_FILE" 2>&1; then
            log_message "✅ Changes committed successfully"
            
            # Push to GitHub
            if git push origin main >> "$LOG_FILE" 2>&1; then
                log_message "✅ Changes pushed to GitHub successfully"
                log_message "🌐 GitHub Pages will deploy automatically"
            else
                log_message "❌ Failed to push to GitHub"
                exit 1
            fi
        else
            log_message "❌ Failed to commit changes"
            exit 1
        fi
    else
        log_message "ℹ️ No changes to deploy"
    fi
    
else
    log_message "❌ Blog generation failed"
    exit 1
fi

log_message "🎉 AUTOMATED BLOG GENERATION COMPLETED"
log_message "📄 Log saved to: $LOG_FILE"

# Keep only last 30 log files
find logs/ -name "cron-blog-*.log" -type f | sort | head -n -30 | xargs rm -f

log_message "🧹 Log cleanup completed"
