name = "it-era-blog-api"
main = "admin-fixed-worker.js"
compatibility_date = "2024-08-24"

# Account ID Bulltech  
account_id = "2842eac6595a0ac8086c76cee3409a24"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
CORS_ORIGIN = "*"

# Development environment
[env.development]
name = "it-era-blog-api-dev"
[env.development.vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "http://localhost:3000"

# Production environment
[env.production]
name = "it-era-blog-api-prod"
[env.production.vars]  
ENVIRONMENT = "production"
CORS_ORIGIN = "https://it-era.pages.dev"

# Routes (commented out for now - will use default workers.dev domain)
# routes = [
#   "it-era-blog-api.andreapanzeri123.workers.dev/*"
# ]