# Cloudflare Workers Configuration for Resend Contact Form
# IT-ERA Contact Form Integration

name = "it-era-resend-contact"
compatibility_date = "2024-01-15"
main = "src/email/resend-contact-worker.js"

# Production deployment
[env.production]
name = "it-era-resend"
route = { pattern = "it-era-email.bulltech.workers.dev/*", zone_name = "bulltech.workers.dev" }

# Custom domain (when ready)
# route = { pattern = "api.it-era.it/contact/*", zone_name = "it-era.it" }

# Environment variables (set via CLI or dashboard)
# wrangler secret put RESEND_API_KEY --env production
# [vars]
# API_VERSION = "1.0"
# FORM_VERSION = "resend-v1"

# KV namespaces for form submissions tracking (optional)
# [[kv_namespaces]]
# binding = "CONTACT_FORMS"
# preview_id = "preview_namespace_id"
# id = "production_namespace_id"

# Analytics and monitoring
[observability]
enabled = true