#:schema node_modules/wrangler/config-schema.json
name = "it-era-admin-auth"
main = "src/auth/auth-worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
API_URL = "https://it-era.pages.dev"
ADMIN_URL = "https://it-era.pages.dev/admin"

# Secrets (set via wrangler secret put)
# JWT_SECRET = "your-secure-jwt-secret"

# Routes for authentication endpoints (commented out due to zone config)
# [[env.production.routes]]
# pattern = "it-era.pages.dev/admin/api/auth/*"
# zone_name = "pages.dev"

# Development environment
[env.development]
name = "it-era-admin-auth-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_URL = "http://localhost:8787"
ADMIN_URL = "http://localhost:8787/admin"

# KV namespaces for session storage (optional)
# [[kv_namespaces]]
# binding = "AUTH_SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 database binding (for production user storage)
# [[d1_databases]]
# binding = "BLOG_DB"
# database_name = "it-era-blog"
# database_id = "your-database-id"
# preview_database_id = "your-preview-database-id"