name = "it-era-chatbot"
main = "src/chatbot/api/chatbot-worker.js"
compatibility_date = "2024-01-23"

# Account ID Bulltech
account_id = "2842eac6595a0ac8086c76cee3409a24"

# KV Namespace for chat sessions
[[kv_namespaces]]
binding = "CHAT_SESSIONS"
id = "988273308c524f4191ab95ed641dc05b"

# Shared KV for configuration (reuse existing)
[[kv_namespaces]]
binding = "SHARED_CONFIG"
id = "e8bd03a1105a46208000adfc1cc84487"

# Environment variables
[vars]
ENVIRONMENT = "production"
MAX_SESSION_DURATION = "1800"
RATE_LIMIT_MESSAGES = "100"

# Development environment
[env.development]
name = "it-era-chatbot-dev"
[env.development.vars]
ENVIRONMENT = "development"
MAX_SESSION_DURATION = "3600"
RATE_LIMIT_MESSAGES = "200"

# Staging environment  
[env.staging]
name = "it-era-chatbot-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
MAX_SESSION_DURATION = "1800"
RATE_LIMIT_MESSAGES = "150"

# Production secrets (da configurare con wrangler secret put)
# OPENAI_API_KEY (futuro per AI avanzata)
# ANTHROPIC_API_KEY (alternativa)