#:schema node_modules/wrangler/config-schema.json
name = "it-era-admin-api"
main = "src/admin/admin-api-worker-complete.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Admin API Worker Configuration
# This worker provides comprehensive admin panel API endpoints

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
API_URL = "https://it-era.pages.dev"
ADMIN_URL = "https://it-era.pages.dev/admin"
SERVICE_NAME = "IT-ERA Admin API"
VERSION = "1.0.0"

# Development environment
[env.development]
name = "it-era-admin-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_URL = "http://localhost:8787"
ADMIN_URL = "http://localhost:8787/admin"
SERVICE_NAME = "IT-ERA Admin API (Dev)"
VERSION = "1.0.0-dev"

# Secrets (set via wrangler secret put)
# JWT_SECRET = "your-super-secure-jwt-secret-key-production"
# ENCRYPTION_KEY = "your-encryption-key-for-sensitive-data"
# API_KEY = "your-internal-api-key"

# KV namespaces for sessions and rate limiting
[[kv_namespaces]]
binding = "ADMIN_SESSIONS"
id = "your-admin-sessions-kv-namespace-id"
preview_id = "your-admin-sessions-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "your-rate-limits-kv-namespace-id"
preview_id = "your-rate-limits-preview-kv-namespace-id"

# D1 database binding for production data storage
[[d1_databases]]
binding = "ADMIN_DB"
database_name = "it-era-admin"
database_id = "your-admin-database-id"
preview_database_id = "your-admin-preview-database-id"

# R2 bucket for media uploads
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "it-era-media"
preview_bucket_name = "it-era-media-preview"

# Routes for admin API endpoints
[[env.production.routes]]
pattern = "it-era.pages.dev/admin/api/*"
zone_name = "pages.dev"

# Worker analytics
[observability]
enabled = true

# Durable Objects for real-time features (future enhancement)
# [[migrations]]
# tag = "v1"
# new_classes = ["AdminRealTimeUpdates"]

# [[durable_objects.bindings]]
# name = "ADMIN_UPDATES"
# class_name = "AdminRealTimeUpdates"

# Cron triggers for maintenance tasks
[[triggers.crons]]
cron = "0 2 * * *"  # Daily at 2 AM UTC