name: IT-ERA Contact Form Handler

on:
  repository_dispatch:
    types: [contact-form-submission]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email via Resend
        uses: actions/github-script@v7
        with:
          script: |
            const payload = context.payload.client_payload;
            
            console.log('📧 Processing contact form:', payload);
            
            // Prepara email per Resend
            const emailData = {
              from: 'noreply@it-era.it',
              to: ['info@it-era.it'],
              subject: `Nuovo contatto IT-ERA: ${payload.full_name} - ${payload.service_type || 'Contatto generico'}`,
              html: `
                <h2>🔧 Nuovo Contatto IT-ERA</h2>
                <p><strong>Nome:</strong> ${payload.full_name}</p>
                <p><strong>Email:</strong> ${payload.email}</p>
                <p><strong>Telefono:</strong> ${payload.phone || 'Non fornito'}</p>
                <p><strong>Azienda:</strong> ${payload.company || 'Non fornita'}</p>
                <p><strong>Servizio:</strong> ${payload.service_type || 'Non specificato'}</p>
                <p><strong>Messaggio:</strong><br>${payload.message || 'Nessun messaggio'}</p>
                <p><strong>Pagina:</strong> ${payload.pagina}</p>
                <p><strong>URL:</strong> ${payload.pageUrl}</p>
                <hr>
                <p><small>Ricevuto il: ${new Date().toLocaleString('it-IT')}</small></p>
              `
            };
            
            // Invia tramite Resend API
            try {
              const response = await fetch('https://api.resend.com/emails', {
                method: 'POST',
                headers: {
                  'Authorization': `Bearer ${{ secrets.RESEND_API_KEY }}`,
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify(emailData)
              });
              
              if (response.ok) {
                const result = await response.json();
                console.log('✅ Email sent successfully:', result.id);
              } else {
                const error = await response.text();
                console.error('❌ Resend API error:', error);
              }
            } catch (error) {
              console.error('❌ Error sending email:', error);
            }
